### PR TITLE
Refactor timestamp parsing code

### PR DESCRIPTION
**Pull request by jwilk**
This should make the timestamp parsing code less awful.

@chilek, could you verify that this change didn't break mobile app 2FA?

### CODE REVIEW

**Comment by chilek** [comment]
Tested it, but didn't have any news financial operations in account history, although no errors or warnings. If we wanna be sure let's wait for next non-empty history account cron task launch.

**Comment by chilek** [comment]
I've got my mbank-cli testing instance reported as registered device. Is there a way to force this instance to be reported as not registered for one time launch?

**Comment by jwilk** [comment]
```console
$ mbank-cli --cookie-jar /dev/null
```

**Comment by chilek** [comment]
so tested and mobile app auth works well.

**Comment by jwilk** [comment]
Great, thanks for testing.

**Comment by chilek** [comment]
> thanks for testing.

You are welcome ;-)

**Pull request merged**
